services:
  db:
    image: postgres:13
    container_name: dundermifflin-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: DundlinMuffin
    ports:
      - "1534:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: